//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Analisis_Proyectos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ventasEntities3 : DbContext
    {
        public ventasEntities3()
            : base("name=ventasEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<categoria> categorias { get; set; }
        public virtual DbSet<cliente> clientes { get; set; }
        public virtual DbSet<detalleVenta> detalleVentas { get; set; }
        public virtual DbSet<factura> facturas { get; set; }
        public virtual DbSet<modoPago> modoPagoes { get; set; }
        public virtual DbSet<modulo> moduloes { get; set; }
        public virtual DbSet<operacione> operaciones { get; set; }
        public virtual DbSet<producto> productoes { get; set; }
        public virtual DbSet<rol> rols { get; set; }
        public virtual DbSet<rol_operacion> rol_operacion { get; set; }
        public virtual DbSet<usuario> usuarios { get; set; }
        public virtual DbSet<vendedor> vendedors { get; set; }
        public virtual DbSet<venta> ventas { get; set; }
    }
}
